name:                traze
version:             0.1.0.0
github:              "iteratec/traze-gameserver"
license:             AGPL
author:              "Benjamin Brunzel"
maintainer:          "benjamin.brunzel@iteratec.de"
copyright:           "2017 Benjamin Brunzel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Tron like mqtt based game server
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/iteratec/traze-gameserver#readme>

dependencies:
- base >= 4.7
- text >= 1.2
- aeson >=1.3
- random >= 1.1
- mtl >= 2.2
- MonadRandom >= 0.5
- colour >= 2.3.4
- time >= 1.8

library:
  source-dirs: src
  dependencies:
  - bytestring >= 0.10
  - uuid >= 1.3
  - stm >= 2.4.5
  - split >= 0.2.3
  - random >= 1.1

executables:
  traze-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - traze
    - monad-loops >= 0.4.3
    - ansi-terminal >= 0.5
    - async >= 2.0.1.5
    - stm >= 2.4.5
    - c-mosquitto >= 0.2.2
    - bytestring >= 0.10
    - uuid >= 1.3
    - yaml-config >= 0.4.0
    - split >= 0.2.3
    - time >= 1.8

  haskell-client:
    main: Client.hs
    source-dirs:
    - client
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Client
    dependencies:
    - traze
    - monad-loops >= 0.4.3
    - ansi-terminal >= 0.5
    - async >= 2.0.1.5
    - stm >= 2.4.5
    - c-mosquitto >= 0.2.2
    - bytestring >= 0.10
    - uuid >= 1.3
    - yaml-config >= 0.4.0
    - split >= 0.2.3
    - options >= 1.2.1.1
    - string-conversions >= 0.4.0.1

tests:
  traze-test:
    main:                Spec.hs
    source-dirs:         
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - traze
    - hspec >= 2.4
    - HUnit >= 1.6
    - QuickCheck >= 2.10
    - uuid >= 1.3

