name:                traze
version:             0.1.0.0
github:              "iteratec/traze-gameserver"
license:             BSD3
author:              "Benjamin Brunzel"
maintainer:          "benjamin.brunzel@iteratec.de"
copyright:           "2017 Benjamin Brunzel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Tron like mqtt based game server
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/iteratec/traze-gameserver#readme>

library:
  source-dirs: src
  dependencies:
  - MonadRandom >= 0.5 && < 0.6
  - aeson >= 1.4 && < 1.5
  - base >= 4.12 && < 4.13
  - colour >= 2.3.4 && < 2.4
  - mtl >= 2.2.2 && < 2.3
  - uuid >= 1.3.13 && < 1.4

tests:
  traze-test:
    main:            Spec.hs
    source-dirs:         
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - traze
    - hspec
    - HUnit
    - QuickCheck
    - uuid

